### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(RZGCS_New)
add_subdirectory(RZGCSContent)
add_subdirectory(RZGCS)
add_subdirectory(App)
add_subdirectory(Dependencies)

qt6_add_resources(${CMAKE_PROJECT_NAME} MainResource
    PREFIX "/qt/qml"
    VERSION 1.0
    FILES 
        "Python/tests/htmlcov/status.json"
        "Python/.vscode/PythonImportHelper-v2-Completion.json"
        ".vscode/extensions.json"
        ".vscode/PythonImportHelper-v2-Completion.json"
        ".qtcreator/project.json"
)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    RZGCSContentplugin
    RZGCSplugin
    Componentsplugin
    com_rzgcs_licensingplugin
    Connectionplugin
    Connectionplugin
    com_rzgcs_licensingplugin
    Componentsplugin
    RZGCSplugin
    RZGCSContentplugin
    Connectionplugin
    Componentsplugin
    RZGCSplugin
    com_rzgcs_licensingplugin
    Connectionplugin
    Componentsplugin
    com_rzgcs_licensingplugin
    RZGCSplugin)