### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(RZGCSContent)
add_subdirectory(RZGCS)
add_subdirectory(App)
add_subdirectory(Dependencies)

qt6_add_resources(${CMAKE_PROJECT_NAME} MainResource
    PREFIX "/qt/qml"
    VERSION 1.0
    FILES 
        "Python/.vscode/PythonImportHelper-v2-Completion.json"
)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    RZGCSContentplugin
    RZGCSplugin)