# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['Python/dronekit_main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('RZGCSContent', 'RZGCSContent'),
        ('Python', 'Python'),
    ],
    hiddenimports=[
        'PySide6.QtCore',
        'PySide6.QtGui', 
        'PySide6.QtQml',
        'PySide6.QtQuick',
        'PySide6.QtWidgets',
        'PySide6.QtNetwork',
        'PySide6.QtOpenGL',
        'PySide6.QtOpenGLWidgets',
        'shiboken6',
        'pymavlink',
        'pymavlink.mavutil',
        'pymavlink.dialects.v20',
        'pymavlink.dialects.v10',
        'serial',
        'serial.tools.list_ports',
        'numpy',
        'matplotlib',
        'cryptography',
        'psutil',
        'requests',
        'threading',
        'datetime',
        'pathlib',
        'enum',
        'collections',
        'collections.abc',
        'dummy_qml_components',
        'dummy_license_controller',
        'mavlink_connector',
        'dronekit_sensor_viewmodel',
        'viewmodel.mission_planner_viewmodel',
        'backend.parameter_manager',
        'dronekit_parameter_viewmodel',
        'backend.flight_control.viewmodels.flight_navigation_viewmodel',
        'backend.firmware.firmware_viewmodel',
        'backend.mavlink_v2_integration',
        'backend.protocol_connection_manager',
        'backend.calibration_controller',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='RZGCS',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='RZGCSContent/Assets/logo_base.png',
) 