site_name: Flottensteuerung
site_description: Flottensteuerung für die Multi-UAV Funktionalität
site_author: RZGS2
site_url: https://rzgs2.github.io/flight_control

theme:
  name: material
  language: de
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Flottensteuerung: fleet.md
  - Flight Phases: flight_phases.md

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: datetime
  - mkdocs-jupyter:
      include_source: true
  - mkdocs-material-extensions 